Settings:
  type: object
  properties:
    showemail:
      type: boolean
      description: Show user email in profile page
    usePagination:
      type: boolean
      description: Toggles between pagination (when enabled), or infinite scrolling (when disabled)
    topicsPerPage:
      type: number
      description: Number of topics displayed on a category page
    postsPerPage:
      type: number
      description: Number of posts displayed on a topic page
    topicPostSort:
      type: string
      description: Default sorting strategy of the posts in of a topic
    openOutgoingLinksInNewTab:
      type: boolean
      description: Whether to automatically open all external links in a new tab
    dailyDigestFreq:
      type: string
      description: How often to receive the scheduled digest from this forum
    showfullname:
      type: boolean
      description: Show user full name in profile page
    followTopicsOnCreate:
      type: boolean
      description: Automatically be notified of new posts in a topic, when you create a topic
    followTopicsOnReply:
      type: boolean
      description:
    restrictChat:
      type: boolean
      description:
    topicSearchEnabled:
      type: boolean
      description:
    categoryTopicSort:
      type: string
      description:
    userLang:
      type: string
      description:
    bootswatchSkin:
      type: string
      description:
    homePageRoute:
      type: string
      description:
    scrollToMyPost:
      type: boolean
      description:
    notificationType_new-chat:
      type: string
      description:
    notificationType_new-reply:
      type: string
      description:
    notificationType_post-edit:
      type: string
      description:
    sendChatNotifications:
      nullable: true
    sendPostNotifications:
      nullable: true
    notificationType_upvote:
      type: string
      description:
    notificationType_new-topic:
      type: string
      description:
    notificationType_follow:
      type: string
      description:
    notificationType_group-invite:
      type: string
      description:
    upvoteNotifFreq:
      type: string
      description:
    notificationType_mention:
      type: string
      description:
    acpLang:
      type: string
      description:
    notificationType_new-register:
      type: string
      description:
    notificationType_post-queue:
      type: string
      description:
    notificationType_new-post-flag:
      type: string
      description:
    notificationType_new-user-flag:
      type: string
      description:
    categoryWatchState:
      type: string
      description:
    notificationType_group-request-membership:
      type: string
      description:
    uid:
      type: number
      description:
      description: A user identifier
  required:
    - showemail
    - usePagination
    - topicsPerPage
    - postsPerPage
    - topicPostSort
    - openOutgoingLinksInNewTab
    - dailyDigestFreq
    - showfullname
    - followTopicsOnCreate
    - followTopicsOnReply
    - restrictChat
    - topicSearchEnabled
    - categoryTopicSort
    - userLang
    - bootswatchSkin
    - homePageRoute
    - scrollToMyPost
    - notificationType_new-chat
    - notificationType_new-reply
    - notificationType_upvote
    - notificationType_new-topic
    - notificationType_follow
    - notificationType_group-invite
    - upvoteNotifFreq
    - acpLang
    - notificationType_new-register
    - notificationType_post-queue
    - notificationType_new-post-flag
    - notificationType_new-user-flag
    - categoryWatchState
    - notificationType_group-request-membership
    - uid