get:
  tags:
    - users
  summary: Get user's settings
  parameters:
    - name: userslug
      in: path
      required: true
      schema:
        type: string
      example: admin
  responses:
    "200":
      description: ""
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../../../components/schemas/UserObject.yaml#/UserObjectFull
              - type: object
                properties:
                  settings:
                    type: object
                    properties:
                      showemail:
                        type: boolean
                      usePagination:
                        type: boolean
                      topicsPerPage:
                        type: number
                      postsPerPage:
                        type: number
                      topicPostSort:
                        type: string
                      openOutgoingLinksInNewTab:
                        type: boolean
                      dailyDigestFreq:
                        type: string
                      showfullname:
                        type: boolean
                      followTopicsOnCreate:
                        type: boolean
                      followTopicsOnReply:
                        type: boolean
                      restrictChat:
                        type: boolean
                      topicSearchEnabled:
                        type: boolean
                      categoryTopicSort:
                        type: string
                      userLang:
                        type: string
                      bootswatchSkin:
                        type: string
                      homePageRoute:
                        type: string
                      scrollToMyPost:
                        type: boolean
                      notificationType_new-chat:
                        type: string
                      notificationType_new-reply:
                        type: string
                      notificationType_post-edit:
                        type: string
                      sendChatNotifications:
                        nullable: true
                      sendPostNotifications:
                        nullable: true
                      notificationType_upvote:
                        type: string
                      notificationType_new-topic:
                        type: string
                      notificationType_follow:
                        type: string
                      notificationType_group-invite:
                        type: string
                      upvoteNotifFreq:
                        type: string
                      notificationType_mention:
                        type: string
                      acpLang:
                        type: string
                      notificationType_new-register:
                        type: string
                      notificationType_post-queue:
                        type: string
                      notificationType_new-post-flag:
                        type: string
                      notificationType_new-user-flag:
                        type: string
                      categoryWatchState:
                        type: string
                      notificationType_group-request-membership:
                        type: string
                      uid:
                        type: number
                        description: A user identifier
                    required:
                      - showemail
                      - usePagination
                      - topicsPerPage
                      - postsPerPage
                      - topicPostSort
                      - openOutgoingLinksInNewTab
                      - dailyDigestFreq
                      - showfullname
                      - followTopicsOnCreate
                      - followTopicsOnReply
                      - restrictChat
                      - topicSearchEnabled
                      - categoryTopicSort
                      - userLang
                      - bootswatchSkin
                      - homePageRoute
                      - scrollToMyPost
                      - notificationType_new-chat
                      - notificationType_new-reply
                      - notificationType_upvote
                      - notificationType_new-topic
                      - notificationType_follow
                      - notificationType_group-invite
                      - upvoteNotifFreq
                      - acpLang
                      - notificationType_new-register
                      - notificationType_post-queue
                      - notificationType_new-post-flag
                      - notificationType_new-user-flag
                      - categoryWatchState
                      - notificationType_group-request-membership
                      - uid
                  languages:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        code:
                          type: string
                        dir:
                          type: string
                        selected:
                          type: boolean
                  acpLanguages:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        code:
                          type: string
                        dir:
                          type: string
                        selected:
                          type: boolean
                  customSettings:
                    type: array
                    items:
                      type: object
                      properties: {}
                      additionalProperties: {}
                  homePageRoutes:
                    type: array
                    items:
                      type: object
                      properties:
                        route:
                          type: string
                        name:
                          type: string
                        selected:
                          type: boolean
                  notificationSettings:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        label:
                          type: string
                        none:
                          type: boolean
                        notification:
                          type: boolean
                        email:
                          type: boolean
                        notificationemail:
                          type: boolean
                  disableEmailSubscriptions:
                    type: number
                  dailyDigestFreqOptions:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                        name:
                          type: string
                        selected:
                          type: boolean
                  bootswatchSkinOptions:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                        selected:
                          type: boolean
                  upvoteNotifFreq:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        selected:
                          type: boolean
                  categoryWatchState:
                    type: object
                    properties:
                      watching:
                        type: boolean
                  disableCustomUserSkins:
                    type: number
                  allowUserHomePage:
                    type: number
                  hideFullname:
                    type: number
                  hideEmail:
                    type: number
                  inTopicSearchAvailable:
                    type: boolean
                  maxTopicsPerPage:
                    type: number
                  maxPostsPerPage:
                    type: number
                  title:
                    type: string
              - $ref: ../../../components/schemas/Breadcrumbs.yaml#/Breadcrumbs
              - $ref: ../../../components/schemas/CommonProps.yaml#/CommonProps